apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: react-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-server
  minReplicas: 3
  maxReplicas: 50
  targetCPUUtilizationPercentage: 65
